export const SquaresFactoryABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_vrfCoordinator', type: 'address' },
      { name: '_vrfKeyHash', type: 'bytes32' },
      { name: '_creationFee', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'createPool',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'squarePrice', type: 'uint256' },
          { name: 'paymentToken', type: 'address' },
          { name: 'maxSquaresPerUser', type: 'uint8' },
          { name: 'payoutPercentages', type: 'uint8[4]' },
          { name: 'teamAName', type: 'string' },
          { name: 'teamBName', type: 'string' },
          { name: 'purchaseDeadline', type: 'uint256' },
          { name: 'vrfTriggerTime', type: 'uint256' },
          { name: 'passwordHash', type: 'bytes32' },
        ],
      },
    ],
    outputs: [{ name: 'pool', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'getPoolsByCreator',
    inputs: [{ name: 'creator', type: 'address' }],
    outputs: [{ type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAllPools',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'pools', type: 'address[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolCount',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolCountByCreator',
    inputs: [{ name: 'creator', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vrfCoordinator',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'creationFee',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vrfFundingAmount',
    inputs: [],
    outputs: [{ type: 'uint96' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultVRFSubscriptionId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultVRFKeyHash',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'admin',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'scoreAdmin',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolCreationPaused',
    inputs: [],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'aavePool',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'wethGateway',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'aWETH',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'aUSDC',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setAaveAddresses',
    inputs: [
      { name: '_pool', type: 'address' },
      { name: '_gateway', type: 'address' },
      { name: '_aWETH', type: 'address' },
      { name: '_aUSDC', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVRFSubscription',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVRFKeyHash',
    inputs: [{ name: 'keyHash', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setCreationFee',
    inputs: [{ name: '_creationFee', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVRFFundingAmount',
    inputs: [{ name: '_amount', type: 'uint96' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setScoreAdmin',
    inputs: [{ name: '_scoreAdmin', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPoolCreationPaused',
    inputs: [{ name: '_paused', type: 'bool' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitScoreToAllPools',
    inputs: [
      { name: 'quarter', type: 'uint8' },
      { name: 'teamAScore', type: 'uint8' },
      { name: 'teamBScore', type: 'uint8' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'triggerVRFForAllPools',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawFees',
    inputs: [{ name: 'to', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferAdmin',
    inputs: [{ name: 'newAdmin', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'PoolCreated',
    inputs: [
      { name: 'pool', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'squarePrice', type: 'uint256', indexed: false },
      { name: 'paymentToken', type: 'address', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'VRFTriggeredForAllPools',
    inputs: [{ name: 'poolsTriggered', type: 'uint256', indexed: false }],
  },
  {
    type: 'event',
    name: 'CreationFeeUpdated',
    inputs: [
      { name: 'oldFee', type: 'uint256', indexed: false },
      { name: 'newFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FeesWithdrawn',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AdminTransferred',
    inputs: [
      { name: 'oldAdmin', type: 'address', indexed: true },
      { name: 'newAdmin', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'ScoreAdminUpdated',
    inputs: [
      { name: 'oldAdmin', type: 'address', indexed: true },
      { name: 'newAdmin', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'VRFSubscriptionCreated',
    inputs: [{ name: 'subscriptionId', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'VRFConsumerAdded',
    inputs: [
      { name: 'subscriptionId', type: 'uint256', indexed: true },
      { name: 'consumer', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'VRFSubscriptionFunded',
    inputs: [
      { name: 'subscriptionId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ScoreSubmittedToAllPools',
    inputs: [
      { name: 'quarter', type: 'uint8', indexed: true },
      { name: 'teamAScore', type: 'uint8', indexed: false },
      { name: 'teamBScore', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PoolCreationPaused',
    inputs: [{ name: 'paused', type: 'bool', indexed: false }],
  },
  {
    type: 'event',
    name: 'AaveAddressesUpdated',
    inputs: [
      { name: 'pool', type: 'address', indexed: false },
      { name: 'gateway', type: 'address', indexed: false },
      { name: 'aWETH', type: 'address', indexed: false },
      { name: 'aUSDC', type: 'address', indexed: false },
    ],
  },
  {
    type: 'error',
    name: 'OnlyAdmin',
    inputs: [],
  },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InsufficientCreationFee',
    inputs: [
      { name: 'sent', type: 'uint256' },
      { name: 'required', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'TransferFailed',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidAddress',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PoolCreationIsPaused',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PoolNameAlreadyExists',
    inputs: [{ name: 'name', type: 'string' }],
  },
  {
    type: 'function',
    name: 'isPoolNameTaken',
    inputs: [{ name: 'name', type: 'string' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'fundVRFSubscription',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelAndWithdrawVRFSubscription',
    inputs: [{ name: 'to', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'VRFSubscriptionCancelled',
    inputs: [
      { name: 'subscriptionId', type: 'uint256', indexed: true },
      { name: 'fundsRecipient', type: 'address', indexed: true },
    ],
  },
  {
    type: 'function',
    name: 'withdrawYieldFromAllPools',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'YieldWithdrawnFromAllPools',
    inputs: [
      { name: 'poolsWithdrawn', type: 'uint256', indexed: false },
    ],
  },
] as const;
